server.servlet.contextPath: /rest-api
springdoc.api-docs.path: /api-docs
spring.web.resources.add-mappings: false

logging:
  level:
    root: INFO

server:
  port: 8443
  ssl:
    key-store-type: "PKCS12"
    key-store: "file:test-client/keys/keystore.p12"
    key-store-password: "changeit"
    key-alias: "xroad-multitenancy-test-client"
    key-password: "changeit"
    client-auth: need
    trust-store: "file:test-client/keys/truststore.p12"
    trust-store-password: "changeit"

security-server:
  # This hostname must match the CN of the security server cert.
  # Also check that it is set as an alias in docker-compose.yaml
  # This way we can use the default certificate of the stand-alone security server
  # and avoid creating yet another cert.
  url: https://def89e4652f4:8443
  client-id: CS/ORG/1111/TestClient
  service-id: CS/ORG/1111/TestService/rest-test

---
spring:
  config:
    activate:
      on-profile: FI-TEST

security-server:
  url: http://fitestsecurityserver:80
  client-id: FI-TEST/ORG/1111/TestClient
  service-id: FI-TEST/ORG/1111/TestService/rest-test

