services:
  ss:
    image: niis/xroad-security-server-standalone:latest
    hostname: ss
    ports:
      - 4000:4000
      - 8080:8080

  test-service:
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/../keys/keys.p12:/app/keys/keys.p12:ro
    ports:
      - 8070:8080
