server.servlet.context-path: /multitenancy-soap-test-service
server.port: 8080
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

jwt-keystore-file: keys/keystore.p12

---
spring:
  config:
    activate:
      on-profile: use_tls

server:
  port: 8443
  ssl:
    key-store-type: "PKCS12"
    key-store: "file:keys/keystore.p12"
    key-store-password: "changeit"
    key-alias: "xroad-multitenancy-test-service-soap-tls-certificate"
    key-password: "changeit"
    client-auth: none
