services:
  ss:
    image: niis/xroad-security-server-standalone:latest
    hostname: ss
    ports:
      - 4000:4000
      - 8080:8080

  test-service:
    build:
      context: ../test-service
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/../test-service/keys/keys.p12:/app/keys/keys.p12:ro
    ports:
      - 8070:8080

  test-client:
    build:
      context: ../test-client
      dockerfile: ./Dockerfile
    ports:
      - 8060:8080
